# Generated by Django 3.2.1 on 2021-05-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedresource',
            old_name='User Name',
            new_name='UserName',
        ),
    ]
