# Generated by Django 3.2.1 on 2021-05-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user name_requestedresource_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedresource',
            old_name='UserName',
            new_name='username',
        ),
    ]
